### ISSUE TITLE
Selecting Dwarf Origin Causes Crash

### ISSUE THREAD

**Issue by HyperDAsriel** [lochnessdragon/OriginsPlus#17]
Ok so essentially, even after adding all the prerequisites for the Origins Plus mod, the Dwarven origin causes a crash when selected.
I cannot seem to find the specific line of code or the path to said line of code after said crash. Here is what the crash message says: 
![image](https://user-images.githubusercontent.com/88693458/178133190-f7e06542-7a4c-4152-870a-2b4f6c8ab861.png)

Here are the relevant parts of the crash report:
Description: Loading entity NBT

java.lang.NoSuchFieldError: WIDTH
	at com.github.originsplus.power.ModifyScalePower.<clinit>(ModifyScalePower.java:13)
	at com.github.originsplus.registry.ModPowers.lambda$null$2(ModPowers.java:45)
	at com.github.originsplus.registry.ModPowers$$Lambda$8577/1042160448.apply(Unknown Source)
	at io.github.apace100.origins.power.factory.PowerFactory$Instance.apply(PowerFactory.java:57)
	at io.github.apace100.origins.power.PowerType.create(PowerType.java:44)
	at io.github.apace100.origins.component.PlayerOriginComponent.lambda$fromTag$5(PlayerOriginComponent.java:239)
	at io.github.apace100.origins.component.PlayerOriginComponent$$Lambda$8571/1742876932.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.component.PlayerOriginComponent.fromTag(PlayerOriginComponent.java:237)
	at io.github.apace100.origins.component.PlayerOriginComponent.readFromNbt(PlayerOriginComponent.java:154)
	at dev.onyxstudios.cca.api.v3.component.ComponentV3.fromTag(ComponentV3.java:74)
	at nerdhub.cardinal.components.api.util.container.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:180)
	at net.minecraft.class_1297.handler$zkm000$fromTag(class_1297.java:3695)
	at net.minecraft.class_1297.method_5651(class_1297.java:1654)
	at net.minecraft.class_3324.method_14600(class_3324.java:341)
	at net.minecraft.class_3324.method_14570(class_3324.java:138)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$bfd000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7684/1385461612.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.originsplus.power.ModifyScalePower.<clinit>(ModifyScalePower.java:13)
	at com.github.originsplus.registry.ModPowers.lambda$null$2(ModPowers.java:45)
	at com.github.originsplus.registry.ModPowers$$Lambda$8577/1042160448.apply(Unknown Source)
	at io.github.apace100.origins.power.factory.PowerFactory$Instance.apply(PowerFactory.java:57)
	at io.github.apace100.origins.power.PowerType.create(PowerType.java:44)
	at io.github.apace100.origins.component.PlayerOriginComponent.lambda$fromTag$5(PlayerOriginComponent.java:239)
	at io.github.apace100.origins.component.PlayerOriginComponent$$Lambda$8571/1742876932.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.component.PlayerOriginComponent.fromTag(PlayerOriginComponent.java:237)
	at io.github.apace100.origins.component.PlayerOriginComponent.readFromNbt(PlayerOriginComponent.java:154)
	at dev.onyxstudios.cca.api.v3.component.ComponentV3.fromTag(ComponentV3.java:74)
	at nerdhub.cardinal.components.api.util.container.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:180)
	at net.minecraft.class_1297.handler$zkm000$fromTag(class_1297.java:3695)

-- Entity being loaded --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 167
	Entity Name: Hyper_D_Asriel
	Entity's Exact location: -120.50, 72.00, 182.50
	Entity's Block location: World: (-121,72,182), Chunk: (at 7,4,6 in -8,11; contains blocks -128,0,176 to -113,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1297.method_5651(class_1297.java:1654)
	at net.minecraft.class_3324.method_14600(class_3324.java:341)
	at net.minecraft.class_3324.method_14570(class_3324.java:138)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$bfd000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7684/1385461612.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lochnessdragon** [comment]
Fixed in 1.19.3!
